services:
    # Factories
    loevgaard_dandomain_stock.factory.stock_movement:
        class: Loevgaard\DandomainStockBundle\Factory\StockMovementFactory
        arguments:
            - "%loevgaard_dandomain_stock.stock_movement_class%"

    # Event Listeners / Subscribers
    loevgaard_dandomain_stock.event_listener.stock_movement:
        class: Loevgaard\DandomainStockBundle\EventListener\OrderSubscriber
        arguments:
            - "@loevgaard_dandomain_stock.factory.stock_movement"
            - "%loevgaard_dandomain_stock.dandomain_order_state_ids%"
        tags:
            - { name: doctrine.event_subscriber }